// Create a custom Cloud9 runner - similar to the Sublime build system
// For more information see http://docs.aws.amazon.com/console/cloud9/create-run-config
{
    "script": [
        "set -e",
        "npx -n=--inspect jest --runInBand --no-cache --coverage $file $args"
    ],
    "working_dir": "/home/ec2-user/environment",
    "selector": "$file",
    "env": {},
    "debugger": "v8",
    "debugport": 9229,
    "info": "Jesting $command",
    "trackId": "Jest"
}
